version: '2'

services:
  express:
    build: backend
    ports:
      - "5000:5000"
    links:
      - database
    volumes:
      - ./backend:/app
  database:
    image: mongo
    ports:
      - "27017:27017"
